
export const mainTournament = {
  id: "vortex",
  title: "COPA VORTEX MENDOZA",
  status: "INSCRIPCIONES ABIERTAS",
  league: "SILPH LEAGUE TOURNAMENT",
  media: "vortex",
  round: "Relámpago",
  date: "20 Mar, 18:00",
  format: "Suizo",
  link: "https://silph.gg/t/gans",
  chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
  description: "La Copa Vortex es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
  results: ["", "", "", "", "", ""],
}

export const tournaments = [
  {
    id: "prismatic",
    title: "COPA PRISMA MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "prismatic",
    round: "Semanal",
    date: "25 Abr, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/t5aa",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Prisma es la nueva copa mensual de Silph League de Abril!.",
    results: ["EfraC89", "ElRyuking", "Cploti", "Gonzamza87", "Lirhygon", "miguelon2023"],
  },
  {
    id: "prismatic",
    title: "COPA PRISMA MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "prismatic",
    round: "Semanal",
    date: "25 Abr, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/t5aa",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Prisma es la nueva copa mensual de Silph League de Abril!.",
    results: ["EfraC89", "ElRyuking", "Cploti", "Gonzamza87", "Lirhygon", "miguelon2023"],
  },
  {
    id: "vortex",
    title: "COPA VORTEX MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "vortex",
    round: "Relámpago",
    date: "20 Mar, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/gans",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Vortex es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
    results: ["Lirhygon", "Ezequielmcf", "EfraC89", "fcuz11", "miguelon2023", "Cofran"],
  },
  {
    id: "laberinto",
    title: "COPA LABERINTO MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "labyrinth",
    round: "Semanal",
    date: "22 Feb, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/cgy3",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Laberinto es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
    results: ["Lirhygon", "EfraC89", "Gonzamza87", "miguelon2023", "fcuz11", "AhmedMusa444"],
  },
  {
    id: "anochecer2",
    title: "COPA ANOCHECER MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "anochecer",
    round: "Relámpago",
    date: "20 Dec, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/bjj4",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Anochecer es la nueva copa mensual de Silph League! Se jugará en la liga Súper (1500 PC), con pokémon que sean de tipo hielo, lucha, tierra, normal o veneno! (Megaevoluciones, Mr. Mime Galar y Mr. Rime baneados) ",
    results: ["EfraC89", "Lirhygon", "NashAsty", "AgustinH", "Romancito007", "TrafalgarGin"],
  },
  {
    id: "anochecer",
    title: "COPA ANOCHECER SEMANAL",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "anochecer",
    round: "Semanal",
    date: "14 Dec, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/yzs2",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Anochecer es la nueva copa mensual de Silph League! Se jugará en la liga Súper (1500 PC), con pokémon que sean de tipo hielo, lucha, tierra, normal o veneno! (Megaevoluciones, Mr. Mime Galar y Mr. Rime baneados) ",
    results: ["Lothikos", "Lirhygon", "fcuz11", "Gonzamza87", "Ezequielmcf", "miguelon2023"],
  },
  {
    id: "pantano2",
    title: "COPA PANTANO SEMANAL",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "pantano",
    round: "Semanal",
    date: "24 Nov, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/s76r",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La copa pantano es la nueva copa temática mensual de Silph League! Modalidad: se juegan rondas de 24 horas de duración, cada ronda son 3 combates en la Liga Súper 1500pc. Cuando?: Lunes 9 de noviembre, 22hs. Tipos permitidos: tipo veneno, tipo fantasma, tipo bicho, tipo planta, tipo agua. Banneos: Tropius, Abomasnow y megaevoluciones.",
    results: ["Gonzamza87", "fcuz11", "Lirhygon", "CepSergio", "miguelon2023", "Ramirito1245"],
  },
  {
    id: "pantano",
    title: "COPA PANTANO MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "pantano",
    round: "Relámpago",
    date: "14 Nov, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/dqes",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La copa pantano es la nueva copa temática mensual de Silph League! Modalidad: se juegan rondas de 24 horas de duración, cada ronda son 3 combates en la Liga Súper 1500pc. Cuando?: Lunes 9 de noviembre, 22hs. Tipos permitidos: tipo veneno, tipo fantasma, tipo bicho, tipo planta, tipo agua. Banneos: Tropius, Abomasnow y megaevoluciones.",
    results: ["Bas5tianXX", "Miikeoll", "Lothikos", "Lirhygon", "Ezequielmcf", "EfraC89"],
  },
  {
    id: "sunrise",
    title: "COPA SUNRISE SEMANAL",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "sunrise",
    round: "Semanal",
    date: "26 Oct, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/ep2h",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La primera copa de la 3ra Temporada de la Silph League.",
    results: ["EfraC89", "CepSergio", "Lirhygon", "miguelon2023", "Colowixtor", "Ezequielmcf"],
  },
  {
    id: "sunrise",
    title: "COPA SUNRISE MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "sunrise",
    round: "Relámpago",
    date: "24 Oct, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/8qqc",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La primera copa de la 3ra Temporada de la Silph League.",
    results: ["Lirhygon", "miguelon2023", "ChanoTapia", "Lothikos", "TrafalgarGin", "DarylMB"],
  },
]

