
export const mainTournament = {
  title: "COPA LABERINTO MENDOZA",
  league: "SILPH LEAGUE TOURNAMENT",
  media: "labyrinth",
  round: "30 minutos",
  date: "27 Feb, 18:00",
  format: "Suizo",
  link: "https://silph.gg/t/cgy3",
  chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
  description: "La Copa Laberinto es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
  results: ["Lirhygon", "EfraC89", "Gonzamza87", "miguelon2023", "fcuz11", "AhmedMusa444"],
}

export const tournaments = [
  {
    id: "vortex",
    title: "COPA VORTEX MENDOZA",
    status: "INSCRIPCIONES ABIERTAS",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "vortex",
    round: "Relámpago",
    date: "20 Mar, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/gans",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Vortex es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
    results: ["", "", "", "", "", ""],
  },
  {
    id: "laberinto",
    title: "COPA LABERINTO MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "labyrinth",
    round: "Relámpago",
    date: "27 Feb, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/cgy3",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Laberinto es la nueva copa mensual de Silph League! La temática del torneo es que los pokémon del equipo no pueden compartir tipos entre ellos.",
    results: ["Lirhygon", "EfraC89", "Gonzamza87", "miguelon2023", "fcuz11", "AhmedMusa444"],
  },
  {
    id: "anochecer2",
    title: "COPA ANOCHECER MENDOZA",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "anochecer",
    round: "Relámpago",
    date: "20 Dec, 18:00",
    format: "Suizo",
    link: "https://silph.gg/t/bjj4",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Anochecer es la nueva copa mensual de Silph League! Se jugará en la liga Súper (1500 PC), con pokémon que sean de tipo hielo, lucha, tierra, normal o veneno! (Megaevoluciones, Mr. Mime Galar y Mr. Rime baneados) ",
    results: ["EfraC89", "Lirhygon", "NashAsty", "AgustinH", "Romancito007", "TrafalgarGin"],
  },
  {
    id: "anochecer",
    title: "COPA ANOCHECER SEMANAL",
    status: "FINALIZADO",
    league: "SILPH LEAGUE TOURNAMENT",
    media: "anochecer",
    round: "Semanal",
    date: "14 Dec, 22:00",
    format: "Suizo",
    link: "https://silph.gg/t/yzs2",
    chat: "https://chat.whatsapp.com/IY0EkLw2RSxGdhclEe15Ay",
    description: "La Copa Anochecer es la nueva copa mensual de Silph League! Se jugará en la liga Súper (1500 PC), con pokémon que sean de tipo hielo, lucha, tierra, normal o veneno! (Megaevoluciones, Mr. Mime Galar y Mr. Rime baneados) ",
    results: ["Lothikos", "Lirhygon", "fcuz11", "Gonzamza87", "Ezequielmcf", "miguelon2023"],
  },
]

